import {
  type SimpleIcon,
  siBiome,
  siClaude,
  siDocker,
  siDotnet,
  siExpress,
  siGithubactions,
  siGitlab,
  siGooglecloud,
  siGooglegemini,
  siHono,
  siLighthouse,
  siModelcontextprotocol,
  siMongodb,
  siN8n,
  siNextdotjs,
  siNodedotjs,
  siOpenapiinitiative,
  siOpentelemetry,
  siPnpm,
  siPostgresql,
  siReact,
  siReactrouter,
  siSass,
  siSocketdotio,
  siStorybook,
  siTypescript,
  siVite,
  siVitest
} from 'simple-icons'

const LOGOS_LONGER_NAMES_FIRST: readonly (readonly [
  string,
  SimpleIcon | null
])[] = [
  ['React Aria', null],
  ['React Native', siReact],
  ['React Router', siReactrouter],
  ['React', siReact],
  ['TypeScript', siTypescript],
  ['Vitest', siVitest],
  ['Vite', siVite],
  ['Sass', siSass],
  ['Storybook', siStorybook],
  ['Node.js', siNodedotjs],
  ['Express', siExpress],
  ['Hono', siHono],
  ['OpenAPI', siOpenapiinitiative],
  ['Socket.IO', siSocketdotio],
  ['MongoDB', siMongodb],
  ['PostgreSQL', siPostgresql],
  ['Biome', siBiome],
  ['Lighthouse', siLighthouse],
  ['Docker', siDocker],
  ['GitLab', siGitlab],
  ['GitHub Actions', siGithubactions],
  ['GCP', siGooglecloud],
  ['OpenTelemetry', siOpentelemetry],
  ['Claude', siClaude],
  ['MCP', siModelcontextprotocol],
  ['n8n', siN8n],
  ['Gemini', siGooglegemini],
  ['Next.js', siNextdotjs],
  ['pnpm', siPnpm],
  ['.NET', siDotnet]
]

export const logoFor = (term: string): SimpleIcon | null =>
  LOGOS_LONGER_NAMES_FIRST.find(([name]) => term.includes(name))?.[1] ?? null
